export default function newRelatz() {
  const relatz = {
    metadata: {
      title: "Senza Titolo",
      subject: "",
      author: "Mario Rossi",
      keywords: [],
      producer: "Relatz",
      creator: "pdf-lib (https://github.com/Hopding/pdf-lib)",
    },
    header: {
      visible: true,
      startFrom: 0,
      elements: [
        {
          type: "row",
          name: "Riga",
          justify: "space-between",
          gap: 10,
          elements: [
            {
              type: "text",
              name: "Titolo",
              content: [
                {
                  text: "Ciao",
                  fontSize: 18,
                  bold: true,
                  italic: false,
                  underline: false,
                  strike: false,
                  color: "#222222",
                  bg: "none",
                },
                {
                  text: " ",
                  fontSize: 18,
                  bold: false,
                  italic: false,
                  underline: false,
                  strike: false,
                  color: "#222222",
                  bg: "none",
                },
                {
                  text: "mondo",
                  fontSize: 18,
                  bold: false,
                  italic: false,
                  underline: true,
                  strike: false,
                  color: "#0077ff",
                  bg: "none",
                },
                {
                  text: "!",
                  fontSize: 18,
                  bold: false,
                  italic: false,
                  underline: false,
                  strike: false,
                  color: "#222222",
                  bg: "none",
                },
                {
                  text: " Come va?",
                  fontSize: 16,
                  bold: false,
                  italic: true,
                  underline: false,
                  strike: false,
                  color: "#333333",
                  bg: "#f3f3f3",
                },
                {
                  text: " Tutto bene spero.",
                  fontSize: 16,
                  bold: false,
                  italic: false,
                  underline: false,
                  strike: false,
                  color: "#111111",
                  bg: "none",
                },
                {
                  text: " (Test barrato)",
                  fontSize: 16,
                  bold: false,
                  italic: false,
                  underline: false,
                  strike: true,
                  color: "#aa0000",
                  bg: "none",
                }
              ],
              align: "left",
              fontFamily: "Helvetica",
              lineHeight: 1.2,
            },
            {
              type: "text",
              name: "Autore",
              content: [],
              align: "center",
              fontFamily: "Times-Roman",
              lineHeight: 1.2
            },
          ],
        },
        {
          type: "line",
          name: "Separatore",
          color: "#000000",
          thickness: 1,
          width: 100,
          align: "center",
          style: "solid",
          margin: { top: 4, bottom: 2 },
        },
      ],
    },
    footer: {
      visible: true,
      startFrom: 0,
      elements: [],
    },
    cover: {
      visible: true,
      elements: [],
    },
    index: {
      visible: true,
      elements: [],
    },
    elements: [],
    margin: { top: 0, bottom: 5, left: 0, right: 0 },
  };

  localStorage.setItem("Relatz", JSON.stringify(relatz));
}
